### ISSUE TITLE
Autocomplete: Highlight Matching Letters In Popup

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#105]
@cu8eeer suggested it somewhere and I never made an issue.

**Comment by Cu8eeeR** [comment]
Thank you!

**Comment by WildcardSearch** [comment]
You're welcome 😄

**Comment by Cu8eeeR** [comment]
It just needs CSS love :)

I propose you to change color of the text, this will be better for reading. Anyway it is mentioned here #80
