### ISSUE TITLE
Templates Not Cached

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#106]
`mentionInitialize` needs to be modified to add templates to `$templatelist`

**Comment by Cu8eeeR** [comment]
Great! Is there any other space how to optimize mentionme?

**Comment by WildcardSearch** [comment]
> Is there any other space how to optimize mentionme?

I am sure there is always room for improvements to be made. I try to keep that in mind when I am going through the code. If I notice something that can be done better, I try to make an issue and at least give it a try.

Of course, I am always open to suggestions.

**Comment by Cu8eeeR** [comment]
I am not a PRO in coding (I have been just in a "learning mode" for over 2 years : )

MentionMe already uses minified JS which can help a lot. Cached templates will be another step. There is no reason to use minified CSS. I have no more ideas what to improve, maybe optimise the code to use lesser queries (if it is possible).

**Comment by WildcardSearch** [comment]
Here is an overview some of the things that have been done since I first released MentionMe 1.0.

- checks were put in place to assure that no hooks are ever added unnecessarily (wrong page, setting off, etc.)
- the name cache was introduced for autocomplete to save queries for user information when being mentioned
- any user who is mentioned in any thread is automatically added to the name cache so even a brand new user will only require one query when they are mentioned the first time and never again unless they become inactive and are removed from the cache
- coincidentally, users with spaces in their name who are in the name cache can be matched without quotes and without a query

The down-side:
- MyAlerts 2.0 now requires us to add a hook in at `global_start` 😢 
- Creating a template for the popup (so that it can be customized by admin) causes us to have to add a hook at `global_intermediate` 😢 

Other than that, we are looking pretty good, I think.

**Comment by Cu8eeeR** [comment]
Thanks for the detailed report 👍 A lot of work have been done :)
