### ISSUE TITLE
Missing space after @username

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#109]
3.1 (minor branch) - last build downloaded 10:58 CET 30/12/2016

If you type in quick reply/full reply
@TESTER text -> it will be shown as @TESTERtext

space is deleted in output (but if you wanna edit your post, the space is here)

**Comment by WildcardSearch** [comment]
Thanks for the report. This is a duplicate of #76, but I see that it has been marked as invalid.

I'll give it a look today.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - it was working fine for me (v3.0 prerelease) IRC. Maybe some changes in code?

**Comment by WildcardSearch** [comment]
It was removed in the first commit for 1.8 https://github.com/WildcardSearch/MentionMe/commit/974c7e6d129cd72974a9638aadb49958161a77a6

**Comment by WildcardSearch** [comment]
I'm not having an issue:

![Quick Reply](http://i.imgur.com/M4GWVes.png)

![Post](http://i.imgur.com/6Bln1jq.png)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - now it works fine on my test board, really weird. I am closing this, if I will see this error again I will contact you. I am sorry .(
