### ISSUE TITLE
Autocomplete: Add autofocus after mention the user from popup

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#110]
When you wanna mention someone in post, and press "enter" you have to click to the text area again to continue (cannot write, there is no "focus"). It should be automatically.

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll take a look at it.

**Comment by WildcardSearch** [comment]
@Cu8eeeR, I'm not experiencing an issue. In my tests, the caret focuses back into the editor after insertion.

https://github.com/WildcardSearch/MentionMe/blob/416b1d74e5bdad3b4ea46ca91a4e3cf6557bddf1/Upload/jscripts/MentionMe/autocomplete.js#L165

and then

https://github.com/WildcardSearch/MentionMe/blob/416b1d74e5bdad3b4ea46ca91a4e3cf6557bddf1/Upload/jscripts/MentionMe/autocomplete.js#L1137, https://github.com/WildcardSearch/MentionMe/blob/416b1d74e5bdad3b4ea46ca91a4e3cf6557bddf1/Upload/jscripts/MentionMe/autocomplete.js#L1331, and https://github.com/WildcardSearch/MentionMe/blob/416b1d74e5bdad3b4ea46ca91a4e3cf6557bddf1/Upload/jscripts/MentionMe/autocomplete.js#L1551

**Comment by Cu8eeeR** [comment]
@WildcardSearch - issue persists (Google Chrome, Win 10 64bit).
http://testingpage.4fan.cz/showthread.php?tid=3&pid=18#pid18 (same user and pw which I sent you via PM)

**Comment by WildcardSearch** [comment]
I just tested and behavior is as expected for me! 😕

**Comment by WildcardSearch** [comment]
...also I notice the mention `@tester text` has a space in it! 😖

**Comment by Cu8eeeR** [comment]
> I just tested and behavior is as expected for me! 😕

Which browser do you have?

**Comment by Cu8eeeR** [comment]
OK tested again:
1) Google Chrome - focus is not working
2) Firefox - focus is working fine

So it is browser related issue.

**Comment by WildcardSearch** [comment]
> Which browser do you have?

I tested in Chrome 55.0.2883.87 m

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I reinstalled my Google Chrome and deactivated all plugins - the issue remains. Anyway it only occurs in "NEW REPLY". In quick reply works fine!
Feel free to close this issue, it seems to be solved.

**Comment by WildcardSearch** [comment]
Okay, I have finally been able to reproduce it.

In Chrome 55 in `newreply.php` in SCEditor mode I see the caret return to the editor and then disappear.

Thanks for the report, I'll see what I can do.

**Comment by WildcardSearch** [comment]
@Cu8eeeR, That works for me in FF and Chrome. If you have time to test, I'd appreciate it.

**Comment by Cu8eeeR** [comment]
I will ASAP (in 2-3 hours).

**Comment by Cu8eeeR** [comment]
Works fine on 2 of 3 PCs where I use Google Chrome. So it seems to be fixed, feel free to close this. Thank you

**Comment by WildcardSearch** [comment]
Thank you. I believe part of the problem is SCEditor bugs.
