### ISSUE TITLE
Add space after mentioned username automatically

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#111]
Add "space" after mentioned usernames automatically.

**Comment by WildcardSearch** [comment]
This used to be the default behavior. In fact, I used to add a space before the mention if it was jammed up against some text and a space after as well, but someone (I can't remember who) complained about it, so I took that behavior out of the plugin.

So, you think I should put it back in or just the space after?

**Comment by Cu8eeeR** [comment]
For me it is better to add a space after the mentioned user. "Automention plugin" from martec has the same behaviour, as well as GitHub or Facebook mention feature. 

It is really difficult to make an universal approach for all users. Personally I vote for space after the username.

**Comment by WildcardSearch** [comment]
That seems fair. I'll confirm this for 3.1
