### ISSUE TITLE
Autocomplete: Popup Style Needs Improvement

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#113]
Trying to achieve something close to @cu8eeer's suggestions in #80

**Comment by WildcardSearch** [comment]
![Autocomplete Popup](http://i.imgur.com/y0abGke.png)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - it is a huge step forward! Really nice!

I suggest these improvements:
- change the right and bottom border - just leave it grey and make shadows smaller
- after the 5th nickname there is a 1-2px useless space
- did you add background-color: #fff for the avatars? It is a must have for transparent png avatars
- maybe you can make the avatars bigger - add 3-5 px - it will use the unused space in the line

I will test it tommorow, really nice, good job friend!

**Comment by WildcardSearch** [comment]
> @WildcardSearch - it is a huge step forward! Really nice!

Thank you.

> I suggest these improvements:

> change the right and bottom border - just leave it grey and make shadows smaller

It is currently 5px. What do you think 2,3?

> after the 5th nickname there is a 1-2px useless space

Yes I know. It has been very difficult to get the popup to size exactly because it is done internally and each editor inherits different style info from the container it is in. I will work on it.

> did you add background-color: #fff for the avatars? It is a must have for transparent png avatars

No, I didn't. Will get that done.

> maybe you can make the avatars bigger - add 3-5 px - it will use the unused space in the line

Are you saying to reduce the padding around the avatar so it is closer to the sides of the `div` or simply make the avatar size larger?

I have taken care to make everything style-able from the style sheet in ACP. To change the avatar width, admin can just edit `.mention_user_avatar` just FYI

> I will test it tommorow, really nice, good job friend!

Thank you. Your help has been invaluable.

**Comment by Cu8eeeR** [comment]
> It is currently 5px. What do you think 2,3?

2px would be enough

> Yes I know. It has been very difficult to get the popup to size exactly because it is done internally and each editor inherits different style info from the container it is in. I will work on it.

It is a small thing :)

> Are you saying to reduce the padding around the avatar so it is closer to the sides of the div or simply make the avatar size larger?

Ok, what about make the font smaller (for the usernames) and make smaller padding to safe some space (or make avatr image bigger)

I know, everybody can adjust size easily via CSS, so just make one universal default style

**Comment by WildcardSearch** [comment]
I went with 3px of the shadow, I think that was a good suggestion. It looks cleaner. At 2px is was a little understated, though.

Yes, I have tested with avatars as small as 10px and as large as 50px and everything still looks pretty good and works as expected.

**Comment by Cu8eeeR** [comment]
Good to hear that :)

For design changes:
mentionme_popup
- border: 2px solid #ddd;
- border-radius: change from 4px do 3px (follow MyBB theme)
img.mention_user_avatar
- margin: 2px 10px 2px 5px; (changed right margin from 5px to 10px -> looks better)
- width and height of avatar: try 30px instead of 25px
mentiome_popup_item
- padding: 2px 3px 2px 3px (top and bottom padding lowered by 3px

![popup](https://cloud.githubusercontent.com/assets/778890/21582153/195c2e74-d04d-11e6-83e8-b69199cef24c.png)


I recommend to change the height of the font used in the popup window and increase the height of the first row (where you type nicknames). Note - the height of the whole popup window must be adjusted. These 3 changes are not applied to the image above.

Try these changes, the output looks better for me. After that we can continue :)



-

**Comment by WildcardSearch** [comment]
Okay thanks. I'll give it a shot after I figure out this style sheet issue.

**Comment by Cu8eeeR** [comment]
I am going to try right now :)

**Comment by WildcardSearch** [comment]
Great! I am going to be getting started on change logs and release docs.

**Comment by WildcardSearch** [comment]
> add background color: #fff for avatar image

I already did that: https://github.com/WildcardSearch/MentionMe/blob/8621b8fdec6570dd3196d82eba6a7abcfe522810/Upload/inc/plugins/MentionMe/install_data.php#L233-L234

> add min-width: 170px or more for popup window

I'll look at it. That might make problems for my sizing algorithms...

> mentionme_popup_input: add padding-left: 3px (now the first letter is difficult for reading).

Okay sounds easy.

**Comment by WildcardSearch** [comment]
> add min-width: 170px or more for popup window

I took a look and the minimum width of the popup is managed internally by the JavaScript object. Placing `min-width` restrictions on the popup causes the hidden scroll bars to malfunction (by not being hidden).

Maybe that is something I could take a look at later, but this close to release, I think I will let it ride.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - OK, just please open a new ticket for this :) If anything I will contact you. 

I have an idea, I will try to adjust the code for this in my free time :)

**Comment by WildcardSearch** [comment]
Okay
