### ISSUE TITLE
Popup: No Fallback for Broken Avatars

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#131]
When a user uses remote avatar and it is broken - does mentionme use default avatar instead or just will show broken image?

**Comment by WildcardSearch** [comment]
I'll have to look at the code to be certain, but I'm pretty sure that it would fall back to the `<img/>` alt tag.

**Comment by Cu8eeeR** [comment]
OK, so it will show default mybb avatar. I cannot try it right now, if I get a chance I will try and let you know.

**Comment by WildcardSearch** [comment]
> OK, so it will show default mybb avatar.

No, you misunderstand me. I am saying that it would not show any image. It would show whatever the contents of that avatar image's `alt` tag:

```html
<img src="remote/avatar.png" alt="[user]'s avatar" />
```

**Comment by Cu8eeeR** [comment]
It would be maybe better to add a fallback -> show default avatar when the user's custom avatar is not available

**Comment by WildcardSearch** [comment]
Yes, I guess you are right. I hadn't considered that.

It really should be built into the MyBB core to always defer to the default avatar!

I'll just edit this issue.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I agree, thats something what should be added, at least into MyBB v2.0.0

**Comment by Cu8eeeR** [comment]
MyBB 1.8.x supports default avatar for users in ACP (settings). It can be used as a fallback

**Comment by WildcardSearch** [comment]
Cool.

I haven't made it to this yet, but I'm thinking of using a little JavaScript to replace any legitimately broken images (not empty field) with the default avatar-- other than that, there isn't too much I can do.

**Comment by Cu8eeeR** [comment]
JS solution would be great :)

![bug](https://user-images.githubusercontent.com/778890/30515907-20a23a3e-9b31-11e7-8532-26ea57971b82.png)

**Comment by WildcardSearch** [comment]
Added JavaScript to automatically reassign `src` properties for broken images to the default avatar.

**Comment by Eldenroot** [comment]
Great! Thank you!
