### ISSUE TITLE
CSS issue when you move between names with arrows (up/down)

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#132]
As title says - no issue on mouse hover, but with arrows the padding of active item is changed a little bit.

**Comment by WildcardSearch** [comment]
Thanks for the report.

**Comment by Cu8eeeR** [comment]
Can you confirm this issue?

**Comment by WildcardSearch** [comment]
I haven't yet, but I will get to it soon. I think I remember that when scrolling with the keyboard there it was a little jumpy at times...I *think*

**Comment by WildcardSearch** [comment]
This fixes it for me.

**Comment by Cu8eeeR** [comment]
I will try tommorow.,, thank you!

**Comment by WildcardSearch** [comment]
You're welcome 👍

**Comment by Cu8eeeR** [comment]
@WildcardSearch - now the moving between usernames with arrows works fine... anyway is possible to "disable the autoscrolling" in the list? I mean that the username is always shown as the first one in the menu. If it is on purpose, let it be :) I am sorry, but I dont know how to describe this better :(

**Comment by WildcardSearch** [comment]
That could easily be made into a setting, but currently it is not possible. If you want to request that as a feature, create an issue and I will get around to it eventually.

**Comment by Cu8eeeR** [comment]
OK, thank you, ticket created #158.

I am closing this one, tested, works fine, thank you!

**Comment by WildcardSearch** [comment]
You're welcome.
