### ISSUE TITLE
Design improvements

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#133]
Here is a summary of my ideas (I will add more when I get time):
1) add padding-left for non matching inputs
![1](https://cloud.githubusercontent.com/assets/778890/22947974/2842bbce-f2fd-11e6-8097-4b68a286412a.png)
2) change font-size from 16->15 px (input and popup window)
3) min-width - I know, you wrote that it is handled by JS, anyway if you can add min-width for the popup body would be nice (150px for example)
4) change border of popup window from 2px to 1px 
5) make popup window's shadows smaller - from 3px to 1px
6) add a bottom-border (separator for input and items in menu) for input line when you lost focus
![6](https://cloud.githubusercontent.com/assets/778890/22948553/3fbd924a-f2ff-11e6-82b2-d30f70ba4a7f.png)

7) make padding for every item in popup smaller -> now it is 2 and 3 px -> lowered by 1px

Here is the result of my proposed changes, yes, not a big deal, just cosmetic changes... maybe you will like some of them ;)
![result](https://cloud.githubusercontent.com/assets/778890/22948505/1453ab3a-f2ff-11e6-9e3c-a0fcb7cd5dea.png)

**Comment by WildcardSearch** [comment]
I'll get those changes made and give it a look when I have time.

Thanks for your time.

**Comment by WildcardSearch** [comment]
1. I'm not sure I understand what you mean.
2. Done.
3. Done.
4. Done.
5. Done.
6. Done.
7. I tried this and it clipped the bottom of the last avatar.

Keep in mind that you can edit the style sheet in ACP and adjust anything you like for every theme. 😄

**Comment by Cu8eeeR** [comment]
Thank you!

1) I mean "id" in the dropdown menu - it is too close to he left border of that window, so add a small space before the "id" would be nice

**Comment by Cu8eeeR** [comment]
I am enclosing screenshots:
1) Space before the text:
![space before](https://cloud.githubusercontent.com/assets/778890/24330472/3284530e-121f-11e7-9cbd-0a3890ccaf5f.png)

**new request/idea:**
If we cannot use min-width of the dropdown window, we should add a small space after the end of the username
![spacafter](https://cloud.githubusercontent.com/assets/778890/24330462/f0781856-121e-11e7-9298-97c9c92694f9.png)

**Comment by WildcardSearch** [comment]
Thanks for the explanations. I'll look at this later today.

**Comment by Cu8eeeR** [comment]
It is still bugged (latest version from the maintance branch with the fix above included; 13.9.2017)

![bug2](https://user-images.githubusercontent.com/778890/30392407-0e8f6216-98bd-11e7-9cff-90b8672eb96f.png)

**Comment by WildcardSearch** [comment]
Working on it. Can you paste that circled name into a comment so that I can test with it (my keyboard doesn't have that key lol)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - of course :) Here they are: "šmoula" and "peťul"

**Comment by WildcardSearch** [comment]
Thank you

**Comment by Eldenroot** [comment]
Note: the last screenshot - it is because the list in the popup menu contains more than 5 usernames (there are more, but you have to scroll down within the list). Possibility to add small tiny elegant scrollbar or something to let users know that there are more usernames in the list?

**Comment by WildcardSearch** [comment]
I'll be honest, my CSS/design skills aren't great, but I will take a look at it and see what I can come up with.

I'm actually going to see how the bug reports come in before I make any changes to MentionMe. If it seems largely bug-free then I feel it would be in our best interest to focus on shifting any further changes to 3.2

In that way I can start the JavaScript rewrite (which has the most potential for introducing bugs) early in the process and it will give us more time to work them out by release.

Thoughts?

**Comment by Eldenroot** [comment]
> I'll be honest, my CSS/design skills aren't great, but I will take a look at it and see what I can come up with.

Same here, there are few small CSS issues, mainly all reported here on GitHub, but I am not sure how to fix them or what would be the best solution. If anything you take check how "automention" plugin from martec looks like and take some idea from there (anyway both plugins are almost identical).

> I'm actually going to see how the bug reports come in before I make any changes to MentionMe. If it seems largely bug-free then I feel it would be in our best interest to focus on shifting any further changes to 3.2

For me there are no known bugs (in v3.1.3) so far :)

> In that way I can start the JavaScript rewrite (which has the most potential for introducing bugs) early in the process and it will give us more time to work them out by release.

I agree, would be really great go ahead and start a work on a rewriting. I am free for testing :)

**Comment by WildcardSearch** [comment]
Okay, then we will agree that unless some big bugs appear that development on the 3.1.x series is closing.

Be forewarned, this might take a while so look for me to disappear into my cave for a while and then I will be back with some updates for testing.

We will leave this open and eventually when 3.2 is close, I'll try to work through the last few suggestions that haven't been implemented.

**Comment by WildcardSearch** [comment]
@Eldenroot I know there were a few things I didn't get done, but I think it might just be easier for you to modify the CSS in `install_data.php` to your liking and then do a pull request? Then I can checkout your fork and see what it looks like and I'm sure I will approve of the changes.

**Comment by Eldenroot** [comment]
@WildcardSearch - there are only one (two) issues remaining:
1) no padding for text in the list without usernames
2) visual issue when the list in the dropdown menu has more than 5 items

The first issue can be fixed by my workaround mentioned in my last PR, but is is hacky and ugly way. wit hthe second one I am not sure, maybe can you add a scrollbar (styled).

**Comment by WildcardSearch** [comment]
1. I am going to wrap the text in a span with a class assigned and then we can just add some CSS in `install_data.php` and it will be solved **and** be customizable by admin-- at least that is the plan 😈 

2. You mean this?

![bug2](https://user-images.githubusercontent.com/778890/30392407-0e8f6216-98bd-11e7-9cff-90b8672eb96f.png)

**Comment by Eldenroot** [comment]
1) Great, sounds good!
2) Yes. it is because there are more than 5 users in the list - "peťul" is not the last name in the list

**Comment by WildcardSearch** [comment]
That should have the first one. There have been a few changes in some other commits. Can you test again and see if the second issue is solved?

**Comment by Eldenroot** [comment]
@WildcardSearch - I will test it in 15 minutes...

**Comment by Eldenroot** [comment]
@WildcardSearch - both are fixed, great! Thank you!

**Comment by WildcardSearch** [comment]
Great!
