### ISSUE TITLE
No popup window is triggered when multiple mentions button is used (quick reply)

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#134]
No popup window is triggered when multiple mentions button is used (quick reply). Users are added but you cannot use "@" for adding more users after that. Only hard refresh helps.

(CKeditor - rin editor)

**Comment by WildcardSearch** [comment]
Thanks for the report. I will take a look as soon as my schedule comes back to this plugin.

**Comment by WildcardSearch** [comment]
What popup window are you talking about? I just took a look and everything seems to working correctly.

**Comment by Cu8eeeR** [comment]
OK, here are steps how to reproduce:
1) in ACP activate: Add a postbit button + Multiple mentions
2) mention at least two posts in one thread
3) in quick reply window click on "Mentions these users now"
4) mentioned usernames are added, BUT if you wanna add more with "@" - popup dropdown menu is not shown and opened (it is not tirggered).

This only happens when you enable Multiple mentions in ACP

**Comment by WildcardSearch** [comment]
Oh okay! I was lost.

Give me a little bit to get back to this. I'm trying to get as much done today as possible before I go back to work tomorrow.

**Comment by Cu8eeeR** [comment]
OK, it happens also when you only hit the mention button (multiple mentions is disabled)

**Comment by WildcardSearch** [comment]
Thanks for the details. I'm gonna rest tonight, but in the morning I'm going to try to get into gear and get some things done.

**Comment by WildcardSearch** [comment]
I can't reproduce this issue, @Cu8eeeR -- I know this had been sitting here a long time, but my tests worked as expected.

**Comment by Cu8eeeR** [comment]
OK, I use CKeditor from @martec - I am not at home right now but the issues still persists according to the reports from users

**Comment by WildcardSearch** [comment]
Perhaps when I get caught up a little more, you would be so kind as to allow me another test account on your board? Perhaps it is because of template differences between your theme and the default-- or maybe I will at least see a JavaScript error that will lead me to the answer.

In any event, thanks for all your help.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - of course I will, I will send you a PM - MyBB community board ASAP. Feel free to test it out :)

**Comment by WildcardSearch** [comment]
PM Received. Thanks

**Comment by WildcardSearch** [comment]
Thankfully I have reproduced the error...finally!

I have begun debugging and we will see how that goes. Honestly, at first look, I see obvious issues with the way the insertion is handled. In any case, I have determined that after using the multi-mention insert, the popup's observation of keypress is lost.

**Comment by Cu8eeeR** [comment]
Yes, thats it.. after using multimention the "@" doenst trigger the popup window, you have to hard refresh your browser to get it working again.

**Comment by WildcardSearch** [comment]
That fixes the problem for me. If you have time to test the update, I'd appreciate it.

**Comment by Cu8eeeR** [comment]
Tested, works fine! Good job!

**Comment by WildcardSearch** [comment]
Thank you.
