### ISSUE TITLE
SQL Error on Install/Activate

### ISSUE THREAD

**Issue by AutoJunkie79** [WildcardSearch/MentionMe#135]
MyBB 1.8.10
PHP 7.1.1
MySQL 5.7.17

Hello, getting the following SQL error when attempting to install & activate:

<img width="613" alt="screen shot 2017-02-19 at 11 11 39 pm" src="https://cloud.githubusercontent.com/assets/25411186/23111963/4f5fa824-f6fa-11e6-947e-d3e6149f43b4.png">

Thanks

**Comment by WildcardSearch** [comment]
Thanks for the report.

**Comment by WildcardSearch** [comment]
@AutoJunkie79 what version of MentionMe are you using?

**Comment by WildcardSearch** [comment]
Never mind. This is a `duplicate` of #126
