### ISSUE TITLE
Avatars broken (wrongly assigned)

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#139]
Latest maintenance version - avatars are assigned wrongly, here is the screenshot:
![1](https://cloud.githubusercontent.com/assets/778890/23586508/ce42d3a4-0196-11e7-8c6e-ea800a06b163.png)

The "green" avatar with cat should be linked to Eldenroot; the image with hearth belongs to Indil-Elda etc.
I use Rin editor from martec; mentionme settings - full text search enabled, thread contributors enabled; postbit button enabled; everything else default

Quite annoying issue.

EDIT: tested with the default settings - same issue :(

EDIT2: I tried to refresh browser cache but without success :(

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll take a look when I can.

**Comment by Cu8eeeR** [comment]
It is really weird, sometime works fine and avatars are assigned correctly but most of the time assigns badly. 

For now I had to disable avatars showing in the popup box, I am looking for a new version :) I know that you are busy so no rush

**Comment by WildcardSearch** [comment]
I honestly haven't even had a chance to look at MentionMe yet. I am trying though.

In testing, all of my fake users had random avatars so I can believe that the bug slipped by me. I'm sure when I get a chance to view the code I will find my mistake.

Sorry for the inconvenience 😢

**Comment by burnacid** [comment]
I've seen the same thing. I've taken a look if I can pinpoint the error. The XMLHTTP request returns the avatar with the correct user. Yet it is displayed wrong.

So the server returns the correct data

**Comment by WildcardSearch** [comment]
Thanks for the reports, unfortunately I still don't have time to look at the code. As soon as I free up some time I will give it a look.

**Comment by WildcardSearch** [comment]
@Cu8eeeR can you give me steps to reproduce this?

![MentionMe Popup](http://i.imgur.com/vyGcjmt.png)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - did you tried with CKeditor (Rin editor) from @martec? I can set a testing account for you on my live board. Let me know

**Comment by WildcardSearch** [comment]
I'm so sorry. I forgot that you said Rin editor. I'll test again.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - hi, any progress? I would like to use this feature :)

**Comment by WildcardSearch** [comment]
As you know, I haven't had much time to work on MentionMe, but in the tests I ran, I was unable to reproduce the issue. I create test users like so: Testuser1, Testuser2, Testuser3... each have an avatar with the corresponding number as an image, ie: 1, 2, 3...

When using the autocomplete feature, they were consistently assigned the correct avatar.

I followed your steps to reproduce the error, but it didn't work. Trust me, I believe you, I just can't make it happen so that I can test.

**Comment by Cu8eeeR** [comment]
OK, I can send you username and pw for testing on my live board via PM (MyBB community forum).

It must be related to editor because it happens all the time, some of the avatars are not loaded at all and the default image is shown instead).

**Comment by Cu8eeeR** [comment]
Another maybe related bug:
- some user avatars are not shown in the dropdown menu (the default one is shown instead). With automention from martec are shown correctly. I have send you PM

**Comment by WildcardSearch** [comment]
@Cu8eeeR in your experience with this issue, did you possibly have users with special characters/international alphabets in their user names?

**Comment by Cu8eeeR** [comment]
Issue is still there :( yes, many of users use special characters in their usernames (ť, ř ,š, č ,ž, ý, á, í, ě etc. - Czech language).

**Comment by WildcardSearch** [comment]
Okay, then I have found an issue where the name cache isn't using `mb_strtolower` that may be causing problems. When I get the next version released, I'd appreciate you giving it a try.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - your fix doesnt solve this annoying bug - check this:

![bug3](https://user-images.githubusercontent.com/778890/30392746-fbe84546-98bd-11e7-9171-17ea17accdce.png)

P.S. latest maintenance version :(

**Comment by Cu8eeeR** [comment]
Another try, different result...
![bug4](https://user-images.githubusercontent.com/778890/30393330-ff892a56-98bf-11e7-9b2a-31e2cb01ad69.png)

**Comment by WildcardSearch** [comment]
😢

**Comment by Cu8eeeR** [comment]
@WildcardSearch - uploaded your latest version on my board -> avatars are working correctly (so far so good, I will test more). However one more issue - sometime the avatar is doubled in the popup menu, see screenshot below (I typed "o", affected user: "šmoula"):
![bug](https://user-images.githubusercontent.com/778890/30524145-59f12f9e-9bee-11e7-8471-0dea4ff16ce3.png)

Anyway really great, awesome work!

**Comment by WildcardSearch** [comment]
Thanks for the feedback. However, that is a separate issue. I'll consider this done.

I'm going to go ahead and release a maintenance version to get these fixes out to the other admins and then go back to work ironing out the rest of the bugs.

As soon as I can get the bugs worked out, I can start rewriting the autocomplete JavaScript so that it will work in Quick Edit...

**Comment by Cu8eeeR** [comment]
> I'm going to go ahead and release a maintenance version to get these fixes out to the other admins and then go back to work ironing out the rest of the bugs.

Yes, I agree, good job! 

> As soon as I can get the bugs worked out, I can start rewriting the autocomplete JavaScript so that it will work in Quick Edit...

Great!
