### ISSUE TITLE
Add abillity to use modals on mentions.

### ISSUE THREAD

**Issue by WhiteNeo** [WildcardSearch/MentionMe#141]
Well i have asked for @Eldenroot to do this and i have worked onto it, so i have added onto my avatars plugin a bridge to use with another mods, in this case is tested with MentionMe and DVZ Mentions.

I have tested on both yours and mine Mentions plugins, and i review DVZ Mentions and can be glitched.

The way to use it and versión of my plugin is 2.9.2 with the core changes to work, if you can test it it would be apreciated and if you add this code i think is usefull for many users.

If you wish to test onl open forum.php file of MentionMe in this path (inc/plugins/MentionMe/forum.php)
Search this function mentionBuild($user)
I have it on line 235 of that file.
In line 268 you must find this:
```PHP
$url = get_profile_link($user['uid']);
// the HTML id property is used to store the uid of the mentioned user for MyAlerts (if installed)
return <<<EOF
{$mybb->settings['mention_display_symbol']}<a id="mention_{$user['uid']}" href="{$url}{$action}"{$evento} class="mentionme_mention">{$username}{$mention_function}
EOF;
```

Replace with:
```PHP
if (function_exists(avatarep_hover_extends))
{
	global $mybb;
	if($mybb->settings['avatarep_menu'] == 1 && $mybb->settings['avatarep_menu_events'] == 2)
	{
		$id = (int)$user['uid'];
		$name = "mention_";
		$mention_function = avatarep_hover_extends($id, $name);
		$action = "?action=avatarep_popup";
		$evento = " onclick=\"return false;\"";				
	}
	else if($mybb->settings['avatarep_menu'] == 1 && $mybb->settings['avatarep_menu_events'] == 1)
	{
		$evento = " onclick=\"MyBB.popupWindow('member.php?uid={$user['uid']}&amp;action=avatarep_popup', null, true); return false;\"";	
	}	
}

$url = get_profile_link($user['uid']);

// the HTML id property is used to store the uid of the mentioned user for MyAlerts (if installed)
return <<<EOF
{$mybb->settings['mention_display_symbol']}<a id="mention_{$user['uid']}" href="{$url}{$action}"{$evento} class="mentionme_mention">{$username}{$mention_function}
EOF;
```

And done !!!

Now modals if avatar have enabled must shou a modal onclick or onmouserover due options in plugin.

Sample extends mentionme:
$id = (int)$user['id']; $name = "mention_";
That in the plugin part of mention calls.

Video of referral:
https://mega.nz/#!nh5kFaDa!xIU47jseVelDkBwnkDswfwVJEFflUgkAJtg6IOnT0M8

**Comment by WildcardSearch** [comment]
Hi @WhiteNeo,

I think some other users have requested this in the past, so perhaps it is worth thinking about. I'm not sure I understand clearly everything you just posted, though. The code find and replace you posted features code that isn't in MentionMe (or at least not exactly) so I don't know how to test.

If you could send a PR, I will gladly pull it and do some testing.

Thanks for contributing to the development of MentionMe! 👍

**Comment by WhiteNeo** [comment]
I have released my latest avatars version:

https://github.com/WhiteNeo/lastposter-avatar-mybb18x-series

So i have added a function to load with MentionMe and others plugins as an
extension.

We need both plugins avatars and mentionme.

And we need to add that core changes to your Mention plugin to loads the
function.

Then we need to configure modalas at your own on avatars, at this point we
have both plugins and the extension to not load profies directly onclick
oly if the plugin of avatars is not present or not configured, i am
rendering a video of ow it works to make more specific this add on.

I have working on my site because i allways use my avatars plugin, but
users who use it have this new improvement if use both plugins.

2017-03-25 15:51 GMT-06:00 Mark Vincent <notifications@github.com>:

**Comment by WhiteNeo** [comment]
Ok the video was rendered.

https://mega.nz/#!GgJCSbjQ!1WR8MSq9cu5cbUle9BVS6j6zSML8WC-5ggeLUW8EP2s

This is what i meant :)

2017-03-25 17:23 GMT-06:00 Leon Kenedy <neogeoman@gmail.com>:

**Comment by Cu8eeeR** [comment]
This is really nice addition, after you click on the mentioned username -> popup is shown (with the most important information) instead of member profile.

**Comment by WhiteNeo** [comment]
Yes and works with both events mouseover and onclick as video shows, and
all is taken by a modal mox inside a template wich is completelly template
to edit at your owns with all the fields on profile, usually ones at least,
all the memprofile array. But it can add userfields and more with
globalization of userfields var, so it is a high extension and usefull
addittion, but you can choose if you wanna use it or not with only a few
clicks to decide it or if mod is not present then Mention Works as usuall :)

I have it into my forum and is pretty cool many users ask me for this and
MentionMe, but i have my own modified version of MentionMe for MyBB 1.6.x
because i have to work in it since Wildcard are dissapear, ha ha ha. Well
we do not know nothing about him and DVZ Mentions are not present, so i
work on my mod to use mentions, due i have to use it since the first 1.8
version like MyAlerts and more, right now i have a very modified version of
myalerts onto my site bassed on first 2.0 for mybb 1.8 so i have to work
until now in every mod i have to make it works at my owns.

But i think in future i have to use original ones due i can not work in all
mods, only if really need it, and now we have active programmers into it,
and is better to use the official ones, i recommend to use yours because i
like it and i have not tested others systems, i hope this addittionn helps
to many users to get a new experience in mybb...

2017-03-26 3:08 GMT-06:00 Eldenroot <notifications@github.com>:

**Comment by WildcardSearch** [comment]
I'll give this some thought. For now I'm just going to focus on the bugs and getting 3.1.1 released.

**Comment by Cu8eeeR** [comment]
Works fine :) really nice addition ;)

**Comment by Cu8eeeR** [comment]
This would be better as a standalone mod - just profile popup windows

**Comment by WildcardSearch** [comment]
>This would be better as a standalone mod - just profile popup windows

I have to agree. @WhiteNeo I think given my schedule, this shouldn't be included in the plugin core. Perhaps you could release it independently...
