### ISSUE TITLE
Add a new settings - open mentioned users in a new tab

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#142]
Related to #141 

For admins who dont use popup userprofiles, we should have an option to open mentioned users in a new tab instead of in existing window.

**Comment by WildcardSearch** [comment]
So you are asking for a new setting that, when set to YES will add `target="_blank"` to the mention anchor link?

**Comment by Cu8eeeR** [comment]
Yes, exactly!

**Comment by WildcardSearch** [comment]
That can be arranged.

**Comment by WildcardSearch** [comment]
Hi @Cu8eeeR, I added the setting, no problems, but when I actually went to test it, I remembered that mention links always go to a new tab in Firefox and Chrome.

Is it that you have your browser set up differently?

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I am sorry, you are right (DVZ mention plugin opens the links in the same tab; mentionme in the new tab). Anyway would be nice to have it?

**Comment by WildcardSearch** [comment]
> Anyway would be nice to have it?

To have what? A setting? If so, do you yes for `target="_blank"` and no to force `target="_self"`?

**Comment by Cu8eeeR** [comment]
Yes, to have a setting :)

**Comment by WildcardSearch** [comment]
Okay, I'll get to it whenever I actually have some time.

**Comment by Cu8eeeR** [comment]
Thank you, I will be waiting for the next release ;)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I use Google Chrome and the links are opened in the same tab, not in the new tab (latest maintance version)

**Comment by WildcardSearch** [comment]
Good info.

I finally got some time off! :D Twenty-five days straight at work, but I am getting a three day weekend. Ready to try to get some things done!

**Comment by Cu8eeeR** [comment]
Tested, works fine, thank you!

**Comment by WildcardSearch** [comment]
😄
