### ISSUE TITLE
Custom Language Files Are Not Loaded

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#143]
Hi, just a question before I will try another approach and try to find any other issue with my board. Are the lang files for frontend working fine for you? Only the English lang is used for all users on my board, my lang file is not loaded.

**Comment by WildcardSearch** [comment]
They are working fine on my end. There are only nine language variables for the front-end.

Where are you experiencing missing language strings?

**Comment by Cu8eeeR** [comment]
I use my own lang file (Czech language). However MentionMe still uses English default original lang file, no way how to load my own translation. Others plugins work fine, so I will try to find what is wrong.

**Comment by Cu8eeeR** [comment]
Ok, so others than English language files (translations) are not loaded. Your English original lang pack is loaded always. :(

**Comment by WildcardSearch** [comment]
There are no translations for me to test with: https://community.mybb.com/mods.php?action=alltranslations&pid=885

**Comment by Cu8eeeR** [comment]
I use only this for front-end (Czech language)
`<?php
/*
 * Plugin Name: MentionMe for MyBB 1.8.x
 * Copyright 2014 WildcardSearch
 * http://www.rantcentralforums.com
 *
 * this file contains language definitions for MentionMe (English)
 */

$l['mention'] = 'zmínit';

// task
$l['mention_task_success'] = 'The MentionMe name cache task ran successfully. Going back {1} days, {2} users were stored at a total cache size of {3}';
$l['mention_task_fail'] = 'MentionMe found no users to cache information for.';

// postbit button
$l['mention_title'] = 'Označit';

// MyAlerts
$l['myalerts_mention_alert'] = '{1} vás zmínil v příspěvku "<strong>{2}</strong>".';
$l['myalerts_setting_mention'] = 'Dostávat upozornění, pokud mě někdo zmíní v příspěvku?';

// multi-mention on post bit
$l['mention_posts_selected'] = 'Vybrali jste jednoho nebo více uživatelů.';
$l['mention_users_now'] = 'Zmínit tyto uživatele nyní';

// mention autocomplete
$l['mention_autocomplete_instructions'] = 'napište uživatelské jméno';

?>`

**Comment by WildcardSearch** [comment]
After some testing I see that it is definitely a bug in MentionMe. The language is being loaded in `mentionMeInitialize` before the board language is established and therefore it always falls back to the default board language (which is english hard coded).

[thread title edited]

**Comment by WildcardSearch** [comment]
That should have it fixed, @Cu8eeeR. If you have time to test I'd appreciate it.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I am sorry, I will test it tommorow.

**Comment by WildcardSearch** [comment]
Don't be sorry, friend. I appreciate all of your help.

P.S. I haven't even looked at the code in two days...SO busy...

**Comment by Cu8eeeR** [comment]
@WildcardSearch - yes, your fix works fine! Custom language translations are loaded properly, thank you!
