### ISSUE TITLE
Hide "@" after user is mentioned

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#145]
Hi,

is possible to hide "@" symbol after you mention the user? So it will add link to the username and hide the "prefix - @" after you post the post. Something like DVZ mentions plugin offer (https://community.mybb.com/mods.php?action=view&pid=29). 

Just an idea, not sure how difficult is that to implement

**Comment by WildcardSearch** [comment]
@Cu8eeeR, we added that in 3.1. See #102

**Comment by Cu8eeeR** [comment]
Sorry, my fault :(
