### ISSUE TITLE
Retrieve Thread Participants

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#146]
OK, I am not sure if it is related to Rin editor or it is fine, but when the thread has less then 5 contributors, the dropdown menu shows every time 5 items. 

For example:
4 thread contributors: User1; User2; User3, User4
1) open dropdown menu by "@"
2) you will see 5 users: User1, User2, User3, User4 and the User5 (User5 has no posts in the thread, only the last registered)
3) User5 is the last registered user on my board (everytime)

If you have only 2 thread contributors, they are shown and the rest 3 are added randomly

Expected behaviour:
It should show only exact number of items if the thread has less than 5 (or what you configure in your ACP plugin settings) contributors. After you type anything it should follow your set value.

You can test it here:
https://www.carcassonneforum.cz/thread-948-post-9347.html#pid9347

**Comment by WildcardSearch** [comment]
Trying to catch up here. The behavior you describe is expected. The number of entries in the popup is determined by a setting in ACP-- regardless of the participation in a specific thread. Remember, thread participants are prioritized into the list, but are only a fraction of the available name cache.

**Comment by WildcardSearch** [comment]
@Cu8eeeR since you've not responded I'm going to close this. The behavior you describe is intended.
