### ISSUE TITLE
1366 - Incorrect integer value: 'NULL' for column 'sid' at row 1

### ISSUE THREAD

**Issue by sdprovider77** [WildcardSearch/MentionMe#148]
Hello to everybody !
Could someone kindly help me? I'm trying to install MentionMe about ACP and when i click 'install' this is the error of mysql : 

> MyBB SQL Error
> 
> MyBB has experienced an internal SQL error and cannot continue.
> 
> SQL Error:
>     1366 - Incorrect integer value: 'NULL' for column 'sid' at row 1
> Query:
>     INSERT INTO mybb_settings (`sid`,`name`,`title`,`description`,`optionscode`,`value`,`disporder`,`gid`) VALUES ('NULL','mention_auto_complete','Auto-Complete Mentions?','YES (default) to autocomplete mentions as they are typed on showthread in Quick Reply and full post/edit pages','yesno','1','10',44), ('NULL','mention_max_items','Maximum Items In Popup','if autocomplete is used, this setting will limit the size of the popup','text','5','20',44), ('NULL','mention_get_thread_participants','Retrieve Thread Participants?','YES (default) to include and proritize highly names of users who have participated in the current thread','yesno','1','30',44), ('NULL','mention_full_text_search','Full Text Search?','YES to match characters in the autocomplete popup anywhere in the username, NO (default) to search for usernames that start with the typed characters','yesno','0','40',44), ('NULL','mention_show_avatars','Show User Avatars?','YES (default) to show user avatars in the autocomplete popup, NO to show usernames only','yesno','1','50',44), ('NULL','mention_add_postbit_button','Add a Postbit Button?','YES to add a button to each post allowing users to tag multiple members to mention (NO by default)','yesno','0','60',44), ('NULL','mention_multiple','Multiple Mentions?','YES (default) to mimic the multi-quote feature or NO to instantly insert the mention on click<br /><br /><strong>The postbit button setting must be set to YES for this setting to take effect</strong>','yesno','0','70',44), ('NULL','mention_format_names','Format Usernames?','YES (default) to format user names according to their display group, NO to format mentions as plain links','yesno','1','80',44), ('NULL','mention_display_symbol','Display Symbol','Set this to @ or another symbol to use to prefix mentions, leave blank for no prefix','text','@','90',44), ('NULL','mention_cache_time','Cache Cut-off Time','The task caches usernames based on when they were last active. In days, specify how far back to go. (Large forums should stick with low numbers to reduce the size of the namecache)','text','7','100',44), ('NULL','mention_minify_js','Minify JavaScript?','YES (default) to serve client-side scripts minified to increase performance, NO to serve beautiful, commented code ;)','yesno','1','110',44), ('NULL','mention_advanced_matching','Enable Advanced Matching?','This option allows user names with whitespace to be processed by MentionMe without the necessity of enclosing user names in double quotes.<br /><br />This feature can greatly increase the server load and is not recommended for large forums.','yesno','0','120',44)

 

Please could someone help me ? 

Thank you very much !

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll have a look asap

**Comment by chope1** [comment]
Still getting the same error on Installation.

`MyBB has experienced an internal SQL error and cannot continue.

SQL Error:
1366 - Incorrect integer value: 'NULL' for column 'sid' at row 1
Query:
INSERT INTO mybb_settings (`sid`,`name`,`title`,`description`,`optionscode`,`value`,`disporder`,`gid`) VALUES ('NULL','mention_auto_complete','Auto-Complete Mentions?','YES (default) to autocomplete mentions as they are typed on showthread in Quick Reply and full post/edit pages','yesno','1','10',37), ('NULL','mention_max_items','Maximum Items In Popup','if autocomplete is used, this setting will limit the size of the popup','text','5','20',37), ('NULL','mention_get_thread_participants','Retrieve Thread Participants?','YES (default) to include and proritize highly names of users who have participated in the current thread','yesno','1','30',37), ('NULL','mention_full_text_search','Full Text Search?','YES to match characters in the autocomplete popup anywhere in the username, NO (default) to search for usernames that start with the typed characters','yesno','0','40',37), ('NULL','mention_show_avatars','Show User Avatars?','YES (default) to show user avatars in the autocomplete popup, NO to show usernames only','yesno','1','50',37), ('NULL','mention_add_postbit_button','Add a Postbit Button?','YES to add a button to each post allowing users to tag multiple members to mention (NO by default)','yesno','0','60',37), ('NULL','mention_multiple','Multiple Mentions?','YES (default) to mimic the multi-quote feature or NO to instantly insert the mention on click<br /><br /><strong>The postbit button setting must be set to YES for this setting to take effect</strong>','yesno','0','70',37), ('NULL','mention_format_names','Format Usernames?','YES (default) to format user names according to their display group, NO to format mentions as plain links','yesno','1','80',37), ('NULL','mention_display_symbol','Display Symbol','Set this to @ or another symbol to use to prefix mentions, leave blank for no prefix','text','@','90',37), ('NULL','mention_cache_time','Cache Cut-off Time','The task caches usernames based on when they were last active. In days, specify how far back to go. (Large forums should stick with low numbers to reduce the size of the namecache)','text','7','100',37), ('NULL','mention_minify_js','Minify JavaScript?','YES (default) to serve client-side scripts minified to increase performance, NO to serve beautiful, commented code ;)','yesno','1','110',37), ('NULL','mention_advanced_matching','Enable Advanced Matching?','This option allows user names with whitespace to be processed by MentionMe without the necessity of enclosing user names in double quotes.<br /><br />This feature can greatly increase the server load and is not recommended for large forums.','yesno','0','120',37)`

**Comment by WildcardSearch** [comment]
Sorry, I haven't had much time to maintian my MyBB plugins lately. The error is caused by the values in inc/plugins/MentionMe/install_data.php for the `SID` field. Changing them to the number `0` rather than `'NULL'` or whatever they are currently will solve the issue.
