### ISSUE TITLE
Autocomplete: Popup Misaligned When Cursor Is Beyond First 'Page'

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#151]
Rin editor + latest maintenance version (13.9.2017) - > go to the full edit of your post and type "@", popup menu is misaligned (Google Chrome) + (again, check the usernames and avatars -> they are again assigned randomly, #139 )

![bug7](https://user-images.githubusercontent.com/778890/30393831-948169d8-98c1-11e7-892f-c76c65193cce.png)

**Comment by WildcardSearch** [comment]
I need to update my copy of Rin Editor and do some testing. Thanks again.

**Comment by Cu8eeeR** [comment]
I use latest version on my board (feel free to test it).

**Comment by WildcardSearch** [comment]
@Cu8eeeR I can't reproduce that error with Chrome 61-- what version are you using?

![screen shot](https://i.imgur.com/i0n9g9I.png)

**Comment by Cu8eeeR** [comment]
Please try to edit any post with a lot of text... .)

**Comment by WildcardSearch** [comment]
> Please try to edit any post with a lot of text... .)

Okay, will do.

> P.S. As you can see, the avatars are wrongly assigned - "ZH6" user has avatar from "šmoula" :(

I understand. Please be patient, I am still testing. It is a little harder for me because I don't know which name goes with each avatar so I have to check profiles.

**Comment by Cu8eeeR** [comment]
> I understand. Please be patient, I am still testing. It is a little harder for me because I don't know which name goes with each avatar so I have to check profiles.

I am sorry, it was only a notice that the bug is not related only to my browser :( Keep good work, I am looking forward! 

> Okay, will do.

Works fine for "short" posts, but with a large amount of text the position of the popup window is bad :(

**Comment by WildcardSearch** [comment]
I will try to see if I can sort that out. Meanwhile I have found another bug... '(

**Comment by WildcardSearch** [comment]
Confirmed. I'll try to get this sorted today or tomorrow.

**Comment by WildcardSearch** [comment]
This issue actually affects Quick Reply as well when using Rin Editor.

**Comment by WildcardSearch** [comment]
This is caused by a bug in Caret.js, the third part library I am using for cursor positioning: https://github.com/ichord/Caret.js/issues/56

I'm going to have to come up with a workaround because the project appears to be dying/dead-- no updates in two years...

**Comment by WildcardSearch** [comment]
This fixes the issue for me. Still testing to ensure that these changes don't break anything else.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I updated my board to your latest maintenance release. Your commit fixes this issue partially - when you scroll during the full edit and use "@" to mention someone -> popup position is miss aligned :( Anyway if you dont scroll over the post, the position is OK (it was bugged before, now works fine). I think it is enough, works fine, thank you very much!

P.S. Here you can test it - https://www.carcassonneforum.cz/thread-948-post-10239.html#pid10239

Thank you very much, one bug less :) Good job!

**Comment by WildcardSearch** [comment]
I'm sorry, but I'm having a hard tim understanding the problem that you are saying still exists. Can you give me simple steps to reproduce?

> Thank you very much, one bug less :) Good job!

I appreciate it. Thanks for putting up with all the delays.

**Comment by Cu8eeeR** [comment]
> I'm sorry, but I'm having a hard tim understanding the problem that you are saying still exists. Can you give me simple steps to reproduce?

I will try to make a video if I find any free time.

I will try to describe this issue again:
1) Go to -> New thread/new post/full edit
2) Press "@" -> popup menu is displayed (5 or more users needed)
3) Try to move in the list with usernames switch with keyboard arrows (down)
4) Selected username is always the first one in the list (on the top of the list). **It would be better to do not scroll (sort) the usernames during the moving within the list by arrows and move the selected usernames to the top of the list.**

I hope it is better to understand :(

**Comment by WildcardSearch** [comment]
Oh, so you are just talking about #158 ?

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I am so sorry, bad ticket (need to go sleep, it is 11PM here) :(

I will try to describe it again in the right ticket :)
