### ISSUE TITLE
Autocomplete: Popup Scrolling Needlessly

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#155]
...in some cases.

**Comment by Cu8eeeR** [comment]
In my opinion it is needed :) at least on my board where we have many similar usernames, you can scroll in the popup window but the scrollbar is missing :(

**Comment by WildcardSearch** [comment]
@Cu8eeeR I think you are misunderstanding this issue. This is about the autocomplete JavaScript attempting to scroll the item list when there are less than one page of items.

And the scroll bar has been hidden purposely in accordance with user requests for the finished look of the popup.
