### ISSUE TITLE
Popup window - keyboard arrow scrolling through usernames

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#158]
As mentioned here: #132 

Make possible to move between usernames with keyboard arrows (up/down) without showing the selected username always as the first one in the list.

**Comment by Cu8eeeR** [comment]
OK, so just make it clear, here is the description:
I will try to describe this issue again:

1) Go to -> New thread/new post/full edit
2) Press "@" -> popup menu is displayed (5 or more users needed)
3) Try to move in the list with usernames switch with keyboard arrows (down)
4) Selected username is always the first one in the list (on the top of the list). It would be better to do not scroll (sort) the usernames during the moving within the list by arrows and move the selected usernames to the top of the list.

**Comment by WildcardSearch** [comment]
Thanks. I'll just have to look at the best way of providing that option for the next version.

**Comment by Eldenroot** [comment]
@WildcardSearch - is that possible somehow?

**Comment by WildcardSearch** [comment]
I actually got it working last night, but I am having this annoying problem like in #132 where the list "jumps" when you reach the bottom. I stayed up too late and got frustrated so I am going to try again tomorrow. If you want I can give you the current version on Discord so maybe you can see what I mean.

**Comment by Eldenroot** [comment]
Fingers crossed!

**Comment by WildcardSearch** [comment]
@Eldenroot there are a few inconsistencies with the visual aspects of the new feature, but I am hoping to solve that in #133
