### ISSUE TITLE
Autocomplete: CKEditor - Quick Reply - Can't Trigger Popup After AJAX Posting

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#160]
With CKEditor installed and replacing Quick Reply, the popup works as is expected until the user posts, and then the popup can no longer be triggered by typing the `@` key.

**Comment by Cu8eeeR** [comment]
Good catch!

**Comment by WildcardSearch** [comment]
Yeah now I have to figure out what is wrong 👅
