### ISSUE TITLE
Some usernames are doubled in the popup menu

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#162]
As I wrote here: https://github.com/WildcardSearch/MentionMe/issues/139 (latest 3.1.2 version)

Sometime the user is doubled in the popup menu, see screenshot below (I typed "o", affected user: "šmoula"):

![bug](https://user-images.githubusercontent.com/778890/30554781-f72c9480-9ca5-11e7-91eb-41f036fd6ab2.png)

EDIT: Only doubled when I type "o", not "š". Fulltext search is enabled.

**Comment by WildcardSearch** [comment]
@Cu8eeeR can you do a little more research for me?

- try going to ACP -> Cache Manager and view `wildcard_plugins` cache-- see if there are multiple instances of the name `šmoula`
- try going to ACP -> Tools & Maintenance -> Task Manager and run the MentionMe Name Cache task from ACP-- if the first test showed multiple instances of `šmoula` then check again after running the task manually

**Comment by Cu8eeeR** [comment]
-> ACP -> Cache Manager - I have two entries for "šmoula" and "smoula"

`[smoula] => Array
                        (
                            [uid] => 92
                            [username] => šmoula
                            [usergroup] => 6
                            [displaygroup] => 0
                            [additionalgroups] => 28,18
                            [ignorelist] => 
                            [avatar] => ./uploads/avatars/avatar_92.gif?dateline=1416382702
                        )

                    [šmoula] => Array
                        (
                            [uid] => 92
                            [username] => šmoula
                            [usergroup] => 6
                            [displaygroup] => 0
                            [additionalgroups] => 28,18
                            [ignorelist] => 
                            [avatar] => ./uploads/avatars/avatar_92.gif?dateline=1416382702
                        )`

**Comment by WildcardSearch** [comment]
Great. I had a hunch that there might be an issue with leftovers from the old name cache (from before we changed to `mb_strtolower`-- the old name cache was built with `strtolower` which converts special characters into standard character equivalents, ie. `š` -> `s`

Let me know if this bug resurfaces.
