### ISSUE TITLE
Add codename for easier update tracking

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#163]
As title says - MentionME codename should be "mention"

https://community.mybb.com/xmlbrowse.php?keywords=mentionme

**Comment by WildcardSearch** [comment]
Great point. I've been meaning to get this done.

P.S. The `codename` for MentionMe is actually just `mention`

**Comment by Eldenroot** [comment]
> P.S. The codename for MentionMe is actually just mention

Yes, I meant that :)
