### ISSUE TITLE
Add Ability To Rebuild Name Cache From ACP Plugin Info

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#171]
When you change a usergroup for a mentioned user (and the new usergroup has a different text color - for example "red"; original usergroup was blue) - mentioned username color is not changed (hard refresh; post edit, etc.).

When you run "MentionMe Name Caching" in ACP -> Task manager the issue is fixed.

Is possible to purge (clean) the cache after group promotion?

It is a minor bug, just a visual glitch.

**Comment by WildcardSearch** [comment]
Let me look at the best way to approach it so that I can say whether it is worth the trouble or not. First impression, I think that it is a good idea.

**Comment by WildcardSearch** [comment]
After thinking about this, I've realized that it goes much deeper than this particular issue. For example, if a user modifies their ignore list, the changes will not take effect until the cache has been rebuilt. However, a user name change will still be handled correctly, but old mentions will, of course, no longer be recognized.

And then you have to consider the possibility of another user changing their name to the previous user name of the first user and now all of the mentions point to their profile, while the poster was referring to the first user...

I think it is too much for this already very complex plugin to hook into every place that a user account can be modified in such a way that it needs to be updated in the name cache, but then again, if a user wishes to ignore another user and it takes 24 hours for the changes to take effect, that will be annoying for admin...

What do you think, @Eldenroot ?

**Comment by Eldenroot** [comment]
Yes, you are right. It is something difficult to solve in a easy way. Anyway it is only a minor "bug". MentionMe cache pruning task runs every 24 hours, after that period all issues are fixed. Maybe can you add a new setting - disable/enable name caching?

**Comment by WildcardSearch** [comment]
Possibly, but I'm thinking that when the issue can be solved by giving admin instructions how to run the task manually will solve the issue (or even maybe giving a quick link in plugin info to rebuild the cache).

> Maybe can you add a new setting - disable/enable name caching?

Give me a chance to think about that. 
- The task would have to be disabled based on the value of that setting.
- The task would have to run on each time the setting was set to `YES` to ensure that the data was up-to-data.
- The query in the forum-side routines would have to be conditionally modified.
- The possibility would exist for users to set the cache setting to 'NO' AND the setting to include thread participants to 'NO' which would mean the autocomplete popup would be empty by default (unless users were mentioned in previous posts in the current thread that are displayed on the same page).

Just thinking out loud...

**Comment by Eldenroot** [comment]
This issue is solved after the task run, there should be added only a note about it. In my opinion . add a note about it, add a link "Rebuild cache" into plugin page for MentionMe.

P.S. For Thank You/Like plugin we use this:
![image](https://user-images.githubusercontent.com/778890/31863829-738f1558-b753-11e7-8f44-c03e35bae1db.png)

**Comment by WildcardSearch** [comment]
I'll see if I can get this done today.
