### ISSUE TITLE
Usegroup style is not used in PM (sent messages)

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#172]
When you mention someone in your PM and then go to the folder with "sent messages" - the username does not use the usergroup style and is not styled. 

Google Chrome, 3.1.4

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll take a look when I can.

**Comment by WildcardSearch** [comment]
@Eldenroot I cannot reproduce that issue on a stock copy of MyBB 1.8.12 with MentionMe 3.1.4 OR 3.2 beta--

![MyBB 1.8.12 - MentionMe 3.1.4 - group formatting in PMs](https://i.imgur.com/wzd7Ffv.png)

**Comment by Eldenroot** [comment]
@WildcardSearch - I will try to debug on my board today,,, give me few hours :)

**Comment by Eldenroot** [comment]
Hmm, I found the issue - it is because I used ctrl+c and ctrl+v - so mentioned usernames in copied text are now html links with default formatting. My bad, I am sorry.

**Comment by WildcardSearch** [comment]
I'm just glad it isn't a big lol
