### ISSUE TITLE
Add a new lang string for mention username link

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#179]
As title says, add title into link with a new lang var. Something like: "Click to show user profile" on mouse hover

**Comment by WildcardSearch** [comment]
To be clear, you want:

```html
<a title="{$some_new_language_string}">{$username}</a>
```

**Comment by Eldenroot** [comment]
Or something like this: 

`<a title="{$lang->some_new_string}">Click to visit {$username}'s profile</a>`

**Comment by WildcardSearch** [comment]
> Or something like this:
> <a title="{$lang->some_new_string}">Click to visit {$username}'s profile</a>

Okay, I am confused. To get specific, we currently use this:

```php
return <<<EOF
{$mybb->settings['mention_display_symbol']}<a id="mention_{$user['uid']}" href="{$url}" class="mentionme_mention"{$target}>{$username}</a>
EOF;
```

I can add a title like this:

return <<<EOF
{$mybb->settings['mention_display_symbol']}<a id="mention_{$user['uid']}" href="{$url}" class="mentionme_mention" title="{$lang->some_new_string}"{$target}>{$username}</a>
EOF;
```

But I cannot affect the `innerHTML` of the mention link because affected mentions would look like `@Click to visit Eldenroot's profile`

**Comment by Eldenroot** [comment]
Ok, what is wrong with 

> @Click to visit Eldenroot's profile

You mean "@"? If yes still better than nothing :)

**Comment by WildcardSearch** [comment]
> Ok, what is wrong with
>> @click to visit Eldenroot's profile

1. Mentions should just have the user name as their text, nothing else.
2. If I made that change everyone would throw rotten tomatoes at me :P

We already talked on Discord. I will add a `title` attribute when there is time.
