### ISSUE TITLE
Rin editor - popup is not displayed when you switch back from source mode

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#200]
Rin editor (martec) - private message - send message

Try to mention anybody -> it will works fine until you switch to source mode and switch back to "normal" mode -> no popup us displayed when you type "@", no error console.

**Comment by WildcardSearch** [comment]
Thanks for the report. I'll take a look when there is time.

**Comment by WildcardSearch** [comment]
That should have it fixed @Eldenroot
