### ISSUE TITLE
Cache is corrupted - some usernames are saved two times

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#202]
There is a problem with cache - when I delete the cache all is fine... but after few days it happens again - some usernames are duplicated so these usernames are doubled in mentionme popup... 

it happens only with usernames with special characters (for example "š"). Please check the code provided below - user "PesBobeš" - this user is saved two times - first is "PesBobes" and the second one is "PesBobeš"

Here is the output of mentionme cache

https://pastebin.com/N232qp9a

**Comment by WildcardSearch** [comment]
I removed the pasted text and placed it in PASTEBIN.

As to the report, thank you and I will look into it when there is time.

**Comment by WildcardSearch** [comment]
That should have it fixed, @Eldenroot.

**Comment by Eldenroot** [comment]
@WildcardSearch - great, I will test in 2 hours... results will be there after few days of testing

**Comment by WildcardSearch** [comment]
Okay great. You will need to test this on a fresh install, though. If the cache is already corrupted, it won't be fixed until the task runs otherwise.

As soon as you give this a thumbs up, I will release 3.2.3 👍

**Comment by Eldenroot** [comment]
Thank you! So I will run task manually.

**Comment by Eldenroot** [comment]
For now it works fine without any issue, thank you!

**Comment by WildcardSearch** [comment]
Great!
