### ISSUE TITLE
Quick edit - not working without page refresh

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#209]
Steps to reproduce:
1) Write something in Quick reply and post
2) Click to "Quick edit" and try to mention someone
3) Popup is not displayed after "@"

How to fix that? Just refresh the page after you made a quick reply, after that try to mention someone in quick edit -> popup is working.

**Comment by WildcardSearch** [comment]
Thanks for the report. Are you using Rin Editor or textarea Quick Edit?

**Comment by Eldenroot** [comment]
I use Rin editor from @martec

**Comment by martec** [comment]
Maybe you can use something like https://github.com/martec/automention/blob/master/jscripts/automention/automention.js#L30
Line 30 until line 33.
function automentionck( local ) {
} 
function above is hook for rin editor,

**Comment by WildcardSearch** [comment]
Thanks, @martec. I have a function in place to re-attach MentionMe's autocomplete to CK Editor once the new post has been submitted, perhaps it was broken during the last update.

I will look at this as soon as I have time.

**Comment by WildcardSearch** [comment]
I'm having trouble reproducing the error. Looking at this GIF, am I missing anything in my steps to attempt to reproduce the issue?

![Rin Editor - Quick Edit - Autocomplete](https://i.imgur.com/fdIbitD.gif)

**Comment by Eldenroot** [comment]
Really strange... try to mention somebody and then do a quick edit...

**Comment by Eldenroot** [comment]
OK, thats really strange. I use Google Chrome and this was mabye reported in rineditor repo, or is it a different bug?

**Comment by WildcardSearch** [comment]
We will just leave this open for now. If time has taught us anything, it is that bugs will eventually surface even if they are hard to reproduce.

If we can reproduce it, I will try my best to fix it. I was hoping I could work on it this weekend because I have today and tomorrow off from work— after this it is back to 7, 12 hour days a week...

**Comment by Eldenroot** [comment]
I updated to the latest Rin editor and it is fine :) so I am closing this one :)
