### ISSUE TITLE
Settings for "Open Mentions In a New Window/Tab?" doesn't work

### ISSUE THREAD

**Issue by SvePu** [WildcardSearch/MentionMe#210]
As wrote above the settings for the new tab option doesn't work.

**Comment by Eldenroot** [comment]
@SvePu - it is working for me without any issues, what version and browser do you use?

**Comment by WildcardSearch** [comment]
Hi @SvePu sorry so slow to reply.

To check if it is working, look at the page source for the mention and ensure that `target"_blank"` is being added to the link. If the target has been added correctly and yet the behavior is not what you expect, then the issue is how your browser treats the target tag in relation to link routing.

**Comment by WildcardSearch** [comment]
Confirmed as an issue with checking the wrong setting. Thanks for the help, @SvePu

**Comment by Eldenroot** [comment]
@WildcardSearch - I am not sure about this, because all mentioned usernames are automatically opened in a new tab... I use this since your release when you added this feature. However maybe it is a browser setting here and this is really bugged. Anyway thank you @SvePu!

**Comment by WildcardSearch** [comment]
Yeah, @Eldenroot, it is a confirmed bug. I referenced `mention_format_names` setting instead of `mention_open_link_in_new_window` in the code.

**Comment by Eldenroot** [comment]
Yes, I understand that but I am just confused that it is fine for me on my side :) thats just my 2 cents ;)

**Comment by WildcardSearch** [comment]
If you remember, there was some concern about the way it worked before. Perhaps your browser (or the browser settings) is causing different behavior? I don't know, for sure, but I am certainly checking the value of the wrong setting in the code :tongue:
