### ISSUE TITLE
MyBB 1.8.15 compatibility

### ISSUE THREAD

**Issue by MaFeSa** [WildcardSearch/MentionMe#212]
Hi, I just updated and now I have this problem with the plugin.
![mybb](https://user-images.githubusercontent.com/1554203/37526090-d0dda0a6-292e-11e8-991c-eec4121863ab.PNG)

Thanks

**Comment by BradRadical** [comment]
Uninstall the plugin and reinstall.

**Comment by MaFeSa** [comment]
@BradRadical I already tried but it does not work

**Comment by BradRadical** [comment]
@MaFeSa I just fixed the issue by doing it. No idea why it's not working for you.

**Comment by MaFeSa** [comment]
@BradRadical I upload again plugin and after reinstalling it it seems solved.
Thanks!
