### ISSUE TITLE
Autocomplete: Recent Thread Participants Query Slow For Larger Forums

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#215]
Brought to my attention by @chack1172

**Comment by Eldenroot** [comment]
@WildcardSearch @chack1172 what about other areas, any way for further optimisation? :)

**Comment by chack1172** [comment]
@Eldenroot tomorrow I'll check if there is something to optimize

**Comment by chack1172** [comment]
I checked all the queries now and I found nothing to optimize @Eldenroot

**Comment by WildcardSearch** [comment]
Guys, I'm still short on time, but when I can test this PR, it should be trivial to get 3.2.4 released.

Thanks for all the help!

**Comment by WildcardSearch** [comment]
I've pulled @chack1172's fix, but talking to a BBO on Discord leads me to believe that we still need to do better. I'm thinking that `ORDER BY MAX(p.pid) DESC` is the trouble. If the `posts` table is very large then having to order all posts will be a heavy load on the host.

Maybe I can just use some PHP to sort the results from a less expensive query.
