### ISSUE TITLE
Width of popup box

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#219]
@WildcardSearch - as I mentioned on Discord - min width is not working for the popup box

![image](https://user-images.githubusercontent.com/778890/41737319-3cdc95bc-758f-11e8-9c2c-ff2d7453f2be.png)

I use min-width: 120px with !important in mentionme.css but as you can see it is overwritten somehow
![image](https://user-images.githubusercontent.com/778890/41737354-5a589c8a-758f-11e8-8f52-c75b1e61fec5.png)

This happens only for "short" usernames, maybe JS is the issue here?

**Comment by WildcardSearch** [comment]
Thanks for the detailed report.

As always, I'm really busy, so I will try to take a look when I get a breather.

**Comment by WildcardSearch** [comment]
Still working a seven days a week...will try to look at this soon. Sorry for the wait.

**Comment by WildcardSearch** [comment]
Okay, @Eldenroot if you want to give this a try as well.
