### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#237]
![image](https://user-images.githubusercontent.com/778890/49702056-98443900-fbf4-11e8-889c-36d5e459a2ba.png)

Disable MyAlerts and check your board :(

**Comment by WildcardSearch** [comment]
Confirmed. Thanks for the report.

**Comment by WildcardSearch** [comment]
Fixed, but that caused #240— both should be fixed now. @Eldenroot

**Comment by Eldenroot** [comment]
great, thank you buddy!
