### ISSUE TITLE
CSS styling issue in text editor

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#238]
There is a small issue, I am not sure if it is intended.

When you mention someone in your post and select the mentioned username -> click on "B" icon in editor to make text bolded, the mentioned username does not follow display setting set in ACP usegroups.

This can be solved by adding CSS font-weight: normal !important; (however this is not the best solution for admins who use bold style for usergroups).

I think mentioned usernames should not be affected by text editor styles. What do you think @WildcardSearch

**Comment by Eldenroot** [comment]
It is quite tricky, not easy to fix :( I am not sure how DVZ mentions handles this, can you test?

**Comment by WildcardSearch** [comment]
**DVZ Mentions 1.05 w/applied formatting:**

![DVZ Mentions 1.05 w/applied formatting](https://i.imgur.com/9ZvvDCn.png)

The more I think about it, I don't feel that this is an issue. First of all, it is avoidable: if the user doesn't wish for the mention to look differently, they are free to wrap it in its own size/format tags; and secondly, maybe it is desirable in some instances to have a large or different colored mention?
