### ISSUE TITLE
I cannot mention anybody after "@" symbol in post

### ISSUE THREAD

**Issue by Eldenroot** [WildcardSearch/MentionMe#250]
![image](https://user-images.githubusercontent.com/778890/62232469-94089e00-b3c6-11e9-96cd-74aeae94b791.png)

When I wanna mention myself in a post, popup is displayed, I choose my nickname and send a post... unfortunately it is not parsed...

**Comment by Eldenroot** [comment]
OK, edit... when you use something like the in the text 
` funkce přes "@" - např.: @"username" , kd`

it is not parsed and the username is not clickable and mentionme is not apply... regex issue?

**Comment by Eldenroot** [comment]
Yes anything after the first "@" is not parsed... it was working fine in older versions...

**Comment by WildcardSearch** [comment]
Confirmed.

I'm working on a fix.

**Comment by WildcardSearch** [comment]
Solution pushed to `maintenance` branch, @Eldenroot

**Comment by Eldenroot** [comment]
Maintenance brach works fine, thank you!

**Comment by WildcardSearch** [comment]
Thank you, so much, @Eldenroot. I will get 3.2.12 released some time this week 👍
