### ISSUE TITLE
"Popup Item" appearing on Quick Reply and Full Reply

### ISSUE THREAD

**Issue by vanessasickles** [WildcardSearch/MentionMe#251]
I updated my forum to myBB 1.8.21, and then updated the MentionMe plugin. Since then, I've experienced a strange issue on the quick and full replies/at the bottom of the page. I've tested this on the default theme as well to ensure it isn't just a theme issue:

![image](https://user-images.githubusercontent.com/29470614/63741735-dacda480-c85b-11e9-9b78-2cc5c6774953.png)
![image](https://user-images.githubusercontent.com/29470614/63741769-fe90ea80-c85b-11e9-9158-7610eab7487a.png)

**Here is the full code of the block that is appearing:**
```<div class="mentionme_popup" style="left: -1000px; top: -1000px;">
	<div class="mentionme_spinner" style="display: none;">
		<img src="images/spinner.gif">
		<span></span>
	</div>
	<div class="mentionme_popup_input_container">
		<input class="mentionme_popup_input" type="text" autocomplete="off">
	</div>
	<div class="mentionme_popup_body"><div class="mentionme_popup_item"><img class="mention_user_avatar" src="https://forum.pokemonurpg.com/images/default_avatar.png">MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM</div></div>
</div>

**Comment by WildcardSearch** [comment]
Hi,

That is likely the result of a long-standing bug that I still can't quite track down.

Usually, uninstalling and installing again will fix this.

**Comment by vanessasickles** [comment]
Thanks for the prompt response. I will give an uninstall + reinstall a try tonight and report back.

**Comment by vanessasickles** [comment]
A little late on my part, but just gave it a shot and it did fix the issue. Best of luck in tracking that down in the future, that's a bizarre one!

**Comment by WildcardSearch** [comment]
I'm glad you got it working 👍
