### ISSUE TITLE
Show first nicks from the thread in popup window

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#55]
It would be nice to show nicknames from the thread where you reply. You know, write @ and then show for example last 5 nicknames from this thread... it would be useful before you type any other letter.

**Comment by WildcardSearch** [comment]
I decided to make this setting-controlled since it will require an extra query.

**Comment by Cu8eeeR** [comment]
Good, I agree!

**Comment by WildcardSearch** [comment]
This seems to have solved #49 as well 😄
