### ISSUE TITLE
Quick Edit support

### ISSUE THREAD

**Issue by Shade-** [WildcardSearch/MentionMe#66]
Quick Edit should be supported by the autocomplete feature.

**Comment by Cu8eeeR** [comment]
+1, also in PMs

**Comment by WildcardSearch** [comment]
> also in PMs

Autocomplete has always been meant to work in PMs. Is it not working for you?

**Comment by Cu8eeeR** [comment]
@WildcardSearch - No, without success

**Comment by WildcardSearch** [comment]
Are you getting any JavaScript errors in console?

Can you look at the page source in the footer section and see if MentionMe's JavaScript is being output?

**Comment by Cu8eeeR** [comment]
@WildcardSearch - fresh board tested - works fine, I am sorry

**Comment by WildcardSearch** [comment]
That's great.

**Comment by WildcardSearch** [comment]
This has been a long time coming, but it will have to wait until the next minor version increase as it will require another huge JavaScript rewrite.

**Comment by Cu8eeeR** [comment]
:(

**Comment by WildcardSearch** [comment]
The problem is that the JavaScript currently doesn't support multiple instances. There can only be one popup at a time. So in `showthread.php`, when a user click Quick Edit they would overwrite the autocomplete object for the Quick Reply window and cause it to fail or both of them to fail.

When I get time, I am going to rewrite the JavaScript as a multi-instance object. This will allow me to provide integration with Quick Edit, Shoutboxes, and other third-party plugins.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - hi! any progress? I really miss this feature :/ (a lot of users complains about it after my board switched from automention to mentionme). They used to mentions in quick reply pretty often.

**Comment by WildcardSearch** [comment]
I really haven't started on it yet. I have my hands full supporting my plugins, and I am in the process of upgrading my forum (and all its modifications) to 1.8.

As soon as things settle down, I'll get back into the code as there are several improvements I'd like to make.

Thanks for your patience.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - thats fine, I will be waiting... last missing feature to make this plugin superior :)

**Comment by WildcardSearch** [comment]
It is certainly going to happen. I am just long overdue to work on my forum. It is still on MyBB 1.6! I am obligated to get things straight with my own site (which was a big motivation to get all my plugins updated to 1.8)

**Comment by Cu8eeeR** [comment]
@WildcardSearch - yeah, thats fine, I understand you. It is a hobby :)

**Comment by WildcardSearch** [comment]
@Shade- @Eldenroot 

...finally.

**Comment by Eldenroot** [comment]
@WildcardSearch - Great! Good job! I am going to test it :)
