### ISSUE TITLE
Language Files

### ISSUE THREAD

**Issue by Tbo29** [WildcardSearch/MentionMe#72]
Sorry to bother you again, but I'ven seen if I translate the language file and place it in the language folder e.g. (deutsch_du) it does not get loaded, I've to replace the original english file. As I have more languages on my boards, is there a workaround?

**Comment by WildcardSearch** [comment]
@Tbo29 can you point me to the changes you made?

**Comment by WildcardSearch** [comment]
This should be fixed.
