### ISSUE TITLE
Will be there update to MyBB 1.8?

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#74]
Hi,
 will be there an updated version for MyBB 1.8? Thanks

**Comment by WildcardSearch** [comment]
@Cu8eR sorry I haven't been able to work on my plugins, but I am getting back into the swing of things. I am currently looking into the SCEditor documentation as that will be the biggest obstacle in getting MentionMe update for MyBB 1.8.

**Comment by WildcardSearch** [comment]
The first draft is in. I'd welcome it if you could test @Cu8eeeR

**Comment by Cu8eeeR** [comment]
Thx, I will later today. can you please add support for CKeditor from
martec in future?

Dne 8. 12. 2016 4:54 napsal uživatel "Mark Vincent" <
notifications@github.com>:

**Comment by WildcardSearch** [comment]
CKEditor? Is that @martec's project?

**Comment by Cu8eeeR** [comment]
Yeah, I moved to ckeditor because sceditor is quite bugged :(

Dne 8. 12. 2016 13:27 napsal uživatel "Mark Vincent" <
notifications@github.com>:

**Comment by WildcardSearch** [comment]
I'll take a look at it. If you will create an issue, it will help me remember.

This will be something I'll look into after initial release for the next minor point version.

**Comment by Cu8eeeR** [comment]
OK, php error (you should add a link or info that the package from Euan is needed

Fatal error: Class 'MybbStuff_MyAlerts_Formatter_AbstractFormatter' not found in /web/inc/plugins/MentionMe/classes/MentionMeFormatter.php on line 10

**Comment by WildcardSearch** [comment]
Thanks for the report, but shouldn't that be included with MyAlerts? I get no such error on localhost.

**Comment by Cu8eeeR** [comment]
OK, but what if the board doesnt use MyAlerts plugin?

**Comment by euantorano** [comment]
Best solution would be to use the class_exists function to check if it exists.

**Comment by WildcardSearch** [comment]
Okay @Cu8eeeR, I had a look and I see what you mean. I was misunderstanding you. I will make a separate issue.

Thanks for the report. I completely missed that.
