### ISSUE TITLE
users old group CSS showing

### ISSUE THREAD

**Issue by damian5000** [WildcardSearch/MentionMe#75]
Not sure what this issue is... Perhaps related to cache? 

All users I've seen are showing up as correct color except 1 who's showing up as standard user. 

He's been in this user group for quite awhile. The only thing I can think of is that his user group was changed after installing the plugin and thus old user group was cached? 

I have checked his account and everything is as it should be (correct user group and show as primary)

**Comment by WildcardSearch** [comment]
I realize that this is an old issue, but yes, it was probably just the cache needing to be updated. You can refresh the name cache at any time by using the tools provided in ACP.
