### ISSUE TITLE
Space after @username

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#76]
Type "@Cu8eR - thx" and click on post

-> the text will be formated to "@Cu8eR- thx"  the space is missing after R

**Comment by WildcardSearch** [comment]
Thanks for the report.

**Comment by Cu8eeeR** [comment]
Can you confirm or not, if not please close this. I reported this issue on MyBB 1.6.x

**Comment by WildcardSearch** [comment]
I just tested on 2.3.3 for MyBB 1.6 and 3.0 BETA for 1.8 and couldn't reproduce.
