### ISSUE TITLE
light version to 1.8

### ISSUE THREAD

**Issue by martec** [WildcardSearch/MentionMe#77]
Hi possible create too light version of mention me to 1.8?

feature type autocomplete etc... make code very bigger... and increase file numbers (js files etc...) that i never will use...
but if has only mention core feature + integration with new myalert is best for me...
to old myalert has version 2.2.5 of mention me ... but this won´t compatible with new version of myalert, so am I compelled to use a full new version of mention me, which personally is not very interesting.

Thanks...

**Comment by WildcardSearch** [comment]
@martec I'm going to close this.

I barely have enough time to maintain one version of my plugins, let alone two. I think that you are underestimating the efficiency of this plugin. The most resource intensive part of MentionMe is the core mention recognition. Features like postbit buttons and autocomplete have negligible effect on the resources of your forum **when enabled**-- when disabled, we are talking about a microsecond-long `if` statement.

As to space on the server, the entire plugin is less than 1MB in size. I respect your opinions and have always had a good working relationship with you, but this time I disagree-- after a lot of research and thought.
