### ISSUE TITLE
MentionMe won't allow certain characters

### ISSUE THREAD

**Issue by zombieking93** [WildcardSearch/MentionMe#79]
Hi, on my forum mentionme won't allow names with | for some reason

**Comment by WildcardSearch** [comment]
Thanks for the report.

**Comment by WildcardSearch** [comment]
Hi @zombieking93, I've had a chance to review your report. The solution is to use the quoted syntax: `@"na|me"` and it will work just fine.

It is a known limitation of this plugin that when using the unquoted version of the tag, special characters will sometimes fail to be matched.
