### ISSUE TITLE
Add user avatars into dropdown menu

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#80]
Hi, something like this - just try to type @ or # (mention threads)

www.mybboost.com

**Comment by WildcardSearch** [comment]
Sounds doable. I have marked this change for the first minor point version of the plugin for 1.8

**Comment by Shade-** [comment]
I you're wondering, I use [At.js](http://ichord.github.io/At.js) which could be nice to have in MentionMe too.

**Comment by WildcardSearch** [comment]
Thanks, @Shade- 

I'll be honest, I really want to handle the auto-completion in-house, mainly because I need to use the built-in name cache and because it will more maintainable.

Built the task has proven very difficult and I might have to use At.js or some other library.

**Comment by Cu8eeeR** [comment]
@WildcardSearch 

This change includes redesign of the dropdown menu. You can take idea from here:
![automention](https://cloud.githubusercontent.com/assets/778890/21563233/58ee9dac-ce80-11e6-9b32-0e4035f1d23e.png)

https://community.mybb.com/thread-173199-post-1256198.html#pid1256198

**Comment by WildcardSearch** [comment]
This is what I'll be working on today. I'll try my best to make it look as nice as possible.

**Comment by WildcardSearch** [comment]
I'm just going to make it match with how the popup already looks for now. Then I will spend some time this evening trying to fiddle with the styling in CSS and JS to get it looking better and acting a little more consistently in a separate commit.

**Comment by WildcardSearch** [comment]
Getting close now...😄

I just have to work on styling the popup and code cleanup then I can release.

Please test! I would greatly appreciate it @anyone
