### ISSUE TITLE
Provide Automated MyAlerts Integration

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#81]
When MentionMe is installed first and MyAlerts is installed later, the integration does not occur. Already in place is a mechanism to warn the user that MyAlerts integration hasn't been done, but I feel that this would be served better by adding a link in ACP plugin info to handle the integration.

**Comment by Cu8eeeR** [comment]
You can check my Thank you/like plugin - it has this feature. Or even better DVZ mentions

**Comment by WildcardSearch** [comment]
Okay thank you. 👍
