### ISSUE TITLE
Add a support for CKEditor (@martec plugin)

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#84]
Add a support for CKEditor (@martec plugin)

Or any other CKeditor plugin (there are two more on mybb mods site)

**Comment by WildcardSearch** [comment]
As it seems to be a popular WYSIWYG editor, I will look into integration.

**Comment by Cu8eeeR** [comment]
Yeah, it is. Mainly because SCeditor is really crappy (bugged), maybe it will be better now when the dev came back after 1 year off

**Comment by WildcardSearch** [comment]
Yes, I saw that the author has made a reappearance. I was a little worried.

I've noticed quite a few issues with SCEditor, but I have never tried CKEditor. I'll give it a look after I am caught up.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - as you can see - really many users replaced the default MyBB editor by CKeditor. Shade added full support for SCeditor and CKeditor in his plugin "Quick references". Maybe you can check the code to make things easier.

**Comment by WildcardSearch** [comment]
That looks good to me @Cu8eeeR 

I did a pretty big rework of the autocomplete JS and it should be a lot easier to maintain now. If you get time to test, let me know how it goes.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I am sorry, I hadnt been in home for last 5 days due to Christmas. I will check ASAP with other improvements you made

**Comment by WildcardSearch** [comment]
Oh yeah, I understand. Enjoy your holiday, my friend. 😄

**Comment by Cu8eeeR** [comment]
@WildcardSearch - works fine, tested with Rin editor v0.7.4

**Comment by WildcardSearch** [comment]
Thanks 😄
