### ISSUE TITLE
Style Sheet Not Getting Cached

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#88]
This had been a recurring problem since the introduction of the style sheet in 2.3.x. Need to find out what is going on here.

**Comment by WildcardSearch** [comment]
@cu8eeer I think I found the issue. If you get time, give this a test.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - it works fine, good job!

**Comment by WildcardSearch** [comment]
Wonderful
