### ISSUE TITLE
Autocomplete: Full Text Search

### ISSUE THREAD

**Issue by WildcardSearch** [WildcardSearch/MentionMe#89]
Currently, the typed text is searched against the **first** characters in usernames. It has been mentioned before and now recently from @cu8eeer in #87 that it would be useful to search for the typed text **anywhere** in the username.

@cu8eeer and anyone else who wants to chime in: Should this be default behavior or should I create a new setting to determine behavior?

**Comment by Cu8eeeR** [comment]
@WildcardSearch - I think that the default behaviour would be easier for coding, but some users dont like this so the option would be better choice (at least there wont be more issues and complains about this in future :) )

**Comment by WildcardSearch** [comment]
That's what I am thinking. I suggest that default behavior be left as-is and a setting introduced to toggle between that and the behavior suggested in this issue.

**Comment by Cu8eeeR** [comment]
Works fine! Good job ,thank you!

**Comment by WildcardSearch** [comment]
You're welcome, @Cu8eeeR 👍 

Thanks for testing.
