### ISSUE TITLE
Mentions: change from username to user ID

### ISSUE THREAD

**Issue by Cu8eeeR** [WildcardSearch/MentionMe#92]
As title says - there is an issue if the user will be renamed. All mentions with old usernames will be invalid.

This can be fixed this way:
- show username in mentioned based on user ID (user ID is always same, the username is not)

**Comment by WildcardSearch** [comment]
This has actually been suggested before in #62, but @jordanmussi and I concluded that, while this approach has its merits, it has the fatal flaw of leaving some sort of weird tag behind:

`<mention:uid>`, or `[mention uid="123"]name[/mention]`

...while the current method only leaves behind the unobtrusive: `@name` or at worst, `@"name"`

Be that as it may, I'd be glad to hear your thoughts after having heard the whole issue.

**Comment by Cu8eeeR** [comment]
@WildcardSearch - yeah, I agree. Unfortunately there is no easy way how to sort this out :(

**Comment by WildcardSearch** [comment]
I guess it will have to stay as-is.

**Comment by Shade-** [comment]
Have you considered replacing the textarea with a contentEditable div, and display the formatted username there? This way, you can potentially use the uid syntax while providing a visual feedback too

**Comment by WildcardSearch** [comment]
@Shade-, even if that were done, after uninstalling the plugin, there would be the same problem with leftover code tags.

**Comment by Shade-** [comment]
Well you could attach an handler to replace all the IDs with the username on uninstall, but I can definitely see your point. It wouldn't be much reliable (the search pattern might replace unwanted pieces of posts) and for big boards it might take ages to loop through all posts.

**Comment by WildcardSearch** [comment]
Yeah, there really isn't a good way to handle it.

Although I must admit, things would be a whole lot simpler if I could just use uid's
